[project]
name = "inferno-cli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Lucien Brule", email = "lucien@lucienbrule.com" }
]
requires-python = ">=3.12"
dependencies = [
    "click>=8.2.1",
]

[project.scripts]
inferno-cli = "inferno_cli:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.dependencies]
inferno_graph = { path = "../inferno-graph", develop = true }
inferno_planner = { path = "../inferno-planner", develop = true }
inferno_tools = { path = "../inferno-tools", develop = true }
